{{- include "toolrank.checkAuth" . }}
{{- if or .Values.auth.apiKey .Values.auth.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toolrank.authSecret" . }}
  labels: {{- include "toolrank.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.auth.apiKey }}
  TOOLRANK_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.auth.apiKeys }}
  keys.json: {{ toJson . | quote }}
  {{- end }}
{{- end }}
